# First, build image: sh devops/docker-image/build_image.sh .

# ALERT - this is a pre-configured for the mysql classicmodels sample database
# see https://apilogicserver.github.io/Docs/Database-Docker/#classicmodels-mysql-docker
# you will need to alter APILOGICPROJECT_SQLALCHEMY_DATABASE_URI (2 lines) for your database & auth
# and, in the case of demo (sqlite), comment them out

# cd <project>  
# sh ./devops/docker-compose-dev-local/docker-compose.sh
# --> builds, runs at localhost:5656

services:

    # TODO - alter this for your database
    # Postgres example: https://github.com/ApiLogicServer/postgres-nw/blob/main/devops/docker-compose-dev-local/docker-compose-dev-local.yml
    mysql-service:
        image: apilogicserver/mysql8.0:latest
        restart: always
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        ports:
            # <Port exposed> : <MySQL Port running inside container>
            - '3308:3306'
        expose:
            # Opens port 3306 on the container
            - '3308'
        volumes:
          - ./mysql:/docker-entrypoint-initdb.d

    api-logic-server:
        image: tylerm007/herbodesonia:latest
        environment:
          - APILOGICPROJECT_VERBOSE=true
          - SECURITY_ENABLED=true
          - APILOGICPROJECT_CLIENT_URI=http://lac0.intergal.coop:5656
          - PYTHONPATH=/app/ApiLogicProject
          - APILOGICSERVER_RUNNING=DOCKER
          - APILOGICPROJECT_SWAGGER_HOST=lac0.intergal.coop
          - APILOGICPROJECT_SWAGGER_PORT=5656
          - APILOGICPROJECT_SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:rootBrasin44@82.223.204.248:3306/herboDeSonia?charset=utf8mb4
          - APILOGICPROJECT_SQLALCHEMY_DATABASE_URI_AUTHENTICATION=mysql+pymysql://root:p@mysql-service:3308/authdb
        expose:
          - 5656
        ports:
          - 5656:5656
        depends_on:
          - mysql-service

    ontimize_app:
      image: tylerm007/ontimize_app:latest
      container_name: ontimize_app
      expose:
        - 8088
      ports:
        - 8088:80
      volumes:
        # local:path-in-container
        - ../../ui/yaml/dist:/home/node  
      depends_on:
        - api-logic-server
      environment:
        - NODE_ENV=production